# creates the postgres db and the app locally
# after executing, access via localhost:8080/swagger-ui.html
version: "3"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgresdata:/var/lib/postgresql/data
    privileged: true
  appserver:
    container_name: server
    hostname: localhost
    image: basic-spring
    ports:
      - "8080:8080"
