# creates the db, the app, and executes the postman tests with newman
version: "3"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
    - 5432:5432
    volumes:
      - ./postgresdata:/var/lib/postgresql/data
    privileged: true
  appserver:
    container_name: server
    hostname: localhost
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  newman:
    image: pstauffer/newman-htmlextra
    volumes:
      - ./test:/etc/newman  # the local /test directory will be copied to the container's /etc/newman directory
    entrypoint: tail -f /dev/null
  wait:
    image: dokku/wait
